[[sample-api]]
== Sample API

[[sample-get-all]]
=== 샘플 목록 조회

`GET /api/samples` 요청을 통해 모든 샘플 목록을 조회할 수 있습니다.

operation::sample-controller-documentation/get-all-samples[snippets='http-request,http-response,response-fields']

[[sample-get-one]]
=== 샘플 단일 조회

`GET /api/samples/{id}` 요청을 통해 특정 ID의 샘플을 조회할 수 있습니다.

operation::sample-controller-documentation/get-sample-by-id[snippets='http-request,path-parameters,http-response,response-fields']

[[sample-create]]
=== 샘플 생성

`POST /api/samples` 요청을 통해 새로운 샘플을 생성할 수 있습니다.

operation::sample-controller-documentation/create-sample[snippets='http-request,request-fields,http-response,response-fields']

[[sample-update]]
=== 샘플 수정

`PUT /api/samples/{id}` 요청을 통해 특정 ID의 샘플을 수정할 수 있습니다.

operation::sample-controller-documentation/update-sample[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

[[sample-delete]]
=== 샘플 삭제

`DELETE /api/samples/{id}` 요청을 통해 특정 ID의 샘플을 삭제할 수 있습니다.

operation::sample-controller-documentation/delete-sample[snippets='http-request,path-parameters,http-response']