spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: ${GITHUB_REDIRECT_URI}
            scope:
              - user:email
              - read:user

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: 86400 # 24 hours
  refresh-token-validity-in-seconds: 604800 # 7 days

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
  region: ${AWS_REGION}
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

logging:
  config: classpath:logback/logback-local.xml
  level:
    joomidang.papersummary: info #필요시 info, trace
    org.hibernate.sql: debug #SQL 쿼리 로깅
